modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="reasonable_smithing_template"
version="1.0.0"
displayName="Reasonable Smithing Template"
displayURL="https://modrinth.com/user/sansen"
logoFile="logo.png"
credits="san"
authors="san"

[[dependencies.reasonable_smithing_template]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




